name: Push Events
on: 
  schedule:
    - cron: '*/5 * * * *'
jobs:
  show-info:
      runs-on: ubuntu-latest
      steps:
      - name: Info
        run: |
          echo "This is a push event on all the branches"
