name: Manual Workflow
on: 
  issues:
    types:
      - opened
jobs:
  run-manual-task:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Info
        run: |
          echo "Running manual task"
